name: Build and Pack

on:
  workflow_call:
    inputs:
      buildenv:
        required: true
        type: string
      
jobs:
  
  BuildAndPack:   
    environment: 
      name: ${{ inputs.buildenv }} 
    runs-on: windows-2019
    steps:
    
    - name: Show Server Variables - LinkReview v6
      run: |
        echo "VAR1_1 ${{ vars.VAR1_1 }}"
        echo "env.name ${{ inputs.buildenv }}"
