name: SPSSCustomApps Main - STG env, manual

on:
  workflow_dispatch:

jobs:
  Variables:   
    environment:
      name: stg 
    runs-on: ubuntu-latest
    outputs:
      currentbranch: ${{ steps.branch-name.outputs.current_branch }}
      packageversion: ${{ steps.package-version.outputs.package_version }}
      repopath: ${{ steps.repo-path.outputs.repo_path }}
      servers: ${{ steps.srv-variab.outputs.ser_vers }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Set package version
      id: package-version
      run : echo "package_version=1.0.0+${{ github.run_number }}" >> $GITHUB_OUTPUT
    
    - name: Set Repo path
      id: repo-path
      run : echo "repo_path=c:\GitHubWorkspace\Repo\SPSSCustomApps" >> $GITHUB_OUTPUT
    
    - name: Set Server Variables
      id: srv-variab
      run: |
       if [[ ${{ github.ref_name }} == "dev" ]]; then
        echo 'ser_vers=[{"server":"GBLON3-DIMDONST.EXTRANET.IEXT","env":"dev"}]' >> $GITHUB_OUTPUT
       elif [[ ${{ github.ref_name }} == "test" ]]; then
        echo 'ser_vers=[{"server":"GBLON3-DIMTONST.EXTRANET.IEXT","env":"test"}]' >> $GITHUB_OUTPUT
       elif [[ ${{ github.ref_name }} == "staging" ]]; then
        echo 'ser_vers=[{"server":"server.stageenv","env":"staging"}]' >> $GITHUB_OUTPUT
       elif [[ ${{ github.ref_name }} == "production" ]]; then
        echo 'ser_vers=[{"server":"1247668-lrappservers01.extranet.iext","env":"N/A"},{"server":"1247670-lrappservers02.extranet.iext","env":"N/A"},{"server":"1247671-lrappservers09.extranet.iext","env":"N/A"},{"server":"1247672-lrappservers10.extranet.iext","env":"N/A"},{"server":"1247852-www01.extranet.iext","env":"N/A"},{"server":"1247854-www02.extranet.iext","env":"N/A"},{"server":"1247855-www05.extranet.iext","env":"N/A"}]' >> $GITHUB_OUTPUT
       fi

    - name: Show Server Variables
      run: |
        echo "currentbranch ${{ steps.branch-name.outputs.current_branch }}"
        echo "packageversion ${{ steps.package-version.outputs.package_version }}"
        echo "repopath ${{ steps.repo-path.outputs.repo_path }}"
        echo "servers ${{ steps.srv-variab.outputs.ser_vers }}"
        echo "env ${{ github.env }}"

  Call-SpssBuild:
    needs: Variables
    uses: ./.github/workflows/SpssBuild.yml
    with:
        currentbranch: ${{ needs.Variables.outputs.currentbranch }}
        packageversion: ${{ needs.Variables.outputs.packageversion }}
    secrets: inherit

  Call-SpssDownloadArtifact:
    if: github.ref_name == 'dev' 
    needs: [Variables, Call-SpssBuild]
    uses: ./.github/workflows/SpssDownloadArtifacts.yml
    with:
        currentbranch: ${{ needs.Variables.outputs.currentbranch }}
        packageversion: ${{ needs.Variables.outputs.packageversion }}
        repopath: ${{ needs.Variables.outputs.repopath }}
    secrets: inherit

  Call-SpssPushArtifact:
    if: github.ref_name == 'dev'
    needs: [Variables, Call-SpssDownloadArtifact]
    uses: ./.github/workflows/SpssPushArtifacts.yml
    with:
        currentbranch: ${{ needs.Variables.outputs.currentbranch }}
        packageversion: ${{ needs.Variables.outputs.packageversion }}
        repopath: ${{ needs.Variables.outputs.repopath }}
        servers: ${{ needs.Variables.outputs.servers }}
    secrets: inherit
