name: Build and Pack

on:
  workflow_call:
    inputs:
      benv:
        required: true
        type: string
      
jobs:
  BuildAndPack:
    environement: ${{ benv }}
    runs-on: windows-2019
    steps:
    
    - name: Show Server Variables - LinkReview v6
      run: |
        echo "LR_QT_CONNSTRING_S ${{ secrets.LR_QT_CONNSTRING_S }}"
        echo LR_SOAP_ADSERVICE ${{ vars.LR_SOAP_ADSERVICE }}
        echo "LR_LOG_PATH ${{ vars.LR_LOG_PATH }}"
        echo "env.name ${{ github.env.name }}"
